######################################################################
##
## Filename: MUX8_1.udo
## Created on: Mon Feb 29 4:27:59 PM Eastern Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
