######################################################################
##
## Filename: comparator_top.udo
## Created on: Mon Feb 15 3:10:06 PM Eastern Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
