######################################################################
##
## Filename: comparator_top_tb.udo
## Created on: Mon Feb 15 2:59:23 PM Eastern Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
