######################################################################
##
## Filename: Coin_Controller.udo
## Created on: Thu Apr 14 10:38:30 AM Eastern Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
