######################################################################
##
## Filename: MISR_TB.udo
## Created on: Thu Apr 28 10:51:10 AM Eastern Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
