######################################################################
##
## Filename: MultiplierWrapper.udo
## Created on: Tue May 03 1:21:53 PM Eastern Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
